# Generated by Django 4.2.2 on 2023-07-17 01:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_amazonitem_merch_img'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AmazonItem',
        ),
    ]
