# Generated by Django 4.2.3 on 2023-07-18 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_order_alter_event_description_alter_event_img_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='merch',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
