# Generated by Django 4.2.3 on 2023-07-18 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_merch_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='merch',
            name='img',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
